{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "4cce6306",
   "metadata": {},
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'detectron2'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
      "\u001b[1;32m~\\AppData\\Local\\Temp/ipykernel_8816/1005325733.py\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m      2\u001b[0m \u001b[1;32mimport\u001b[0m \u001b[0mjson\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      3\u001b[0m \u001b[1;32mimport\u001b[0m \u001b[0mxml\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0metree\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mElementTree\u001b[0m \u001b[1;32mas\u001b[0m \u001b[0mET\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m----> 4\u001b[1;33m \u001b[1;32mfrom\u001b[0m \u001b[0mdetectron2\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mstructures\u001b[0m \u001b[1;32mimport\u001b[0m \u001b[0mBoxMode\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m      5\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      6\u001b[0m \u001b[1;32mdef\u001b[0m \u001b[0mconvert_xml_to_coco\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mxml_dir\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mimage_dir\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0moutput_json\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mModuleNotFoundError\u001b[0m: No module named 'detectron2'"
     ]
    }
   ],
   "source": [
    "import os\n",
    "import json\n",
    "import xml.etree.ElementTree as ET\n",
    "from detectron2.structures import BoxMode\n",
    "\n",
    "def convert_xml_to_coco(xml_dir, image_dir, output_json):\n",
    "    dataset_dicts = []\n",
    "\n",
    "    for filename in os.listdir(xml_dir):\n",
    "        if filename.endswith('.xml'):\n",
    "            record = {}\n",
    "            tree = ET.parse(os.path.join(xml_dir, filename))\n",
    "            root = tree.getroot()\n",
    "\n",
    "            # Get image information\n",
    "            image_name = filename.replace('.xml', '.jpg')  # Assuming your images have jpg extension\n",
    "            img_path = os.path.join(image_dir, image_name)\n",
    "            height, width = cv2.imread(img_path).shape[:2]\n",
    "\n",
    "            record[\"file_name\"] = img_path\n",
    "            record[\"image_id\"] = int(filename.replace('.xml', ''))\n",
    "            record[\"height\"] = height\n",
    "            record[\"width\"] = width\n",
    "\n",
    "            objs = []\n",
    "            for obj in root.findall('object'):\n",
    "                category = obj.find('name').text\n",
    "                bbox = obj.find('bndbox')\n",
    "                xmin = float(bbox.find('xmin').text)\n",
    "                ymin = float(bbox.find('ymin').text)\n",
    "                xmax = float(bbox.find('xmax').text)\n",
    "                ymax = float(bbox.find('ymax').text)\n",
    "\n",
    "                obj_dict = {\n",
    "                    \"bbox\": [xmin, ymin, xmax, ymax],\n",
    "                    \"bbox_mode\": BoxMode.XYXY_ABS,\n",
    "                    \"category_id\": category\n",
    "                }\n",
    "                objs.append(obj_dict)\n",
    "\n",
    "            record[\"annotations\"] = objs\n",
    "            dataset_dicts.append(record)\n",
    "\n",
    "    with open(output_json, 'w') as json_file:\n",
    "        json.dump(dataset_dicts, json_file)\n",
    "\n",
    "xml_annotation_dir = \"H:\\\\my dataset\\\\Annotations\"\n",
    "image_dir = \"H:\\\\my dataset\\\\Images\"\n",
    "output_json = \"instances_train.json\"\n",
    "\n",
    "convert_xml_to_coco(xml_annotation_dir, image_dir, output_json)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "85a2490d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\asus\\anaconda3\\lib\\site-packages\\conda\\exceptions.py\", line 1125, in __call__\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\Users\\asus\\anaconda3\\lib\\site-packages\\conda\\cli\\main.py\", line 86, in main_subshell\n",
      "    exit_code = do_call(args, p)\n",
      "  File \"C:\\Users\\asus\\anaconda3\\lib\\site-packages\\conda\\cli\\conda_argparse.py\", line 91, in do_call\n",
      "    module = import_module(relative_mod, __name__.rsplit('.', 1)[0])\n",
      "  File \"C:\\Users\\asus\\anaconda3\\lib\\importlib\\__init__.py\", line 127, in import_module\n",
      "    return _bootstrap._gcd_import(name[level:], package, level)\n",
      "  File \"<frozen importlib._bootstrap>\", line 1030, in _gcd_import\n",
      "  File \"<frozen importlib._bootstrap>\", line 1007, in _find_and_load\n",
      "  File \"<frozen importlib._bootstrap>\", line 986, in _find_and_load_unlocked\n",
      "  File \"<frozen importlib._bootstrap>\", line 680, in _load_unlocked\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 850, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 228, in _call_with_frames_removed\n",
      "  File \"C:\\Users\\asus\\anaconda3\\lib\\site-packages\\conda\\cli\\main_install.py\", line 8, in <module>\n",
      "    from .install import install\n",
      "  File \"C:\\Users\\asus\\anaconda3\\lib\\site-packages\\conda\\cli\\install.py\", line 18, in <module>\n",
      "    from ..core.index import calculate_channel_urls, get_index\n",
      "  File \"C:\\Users\\asus\\anaconda3\\lib\\site-packages\\conda\\core\\index.py\", line 14, in <module>\n",
      "    from .package_cache_data import PackageCacheData\n",
      "  File \"C:\\Users\\asus\\anaconda3\\lib\\site-packages\\conda\\core\\package_cache_data.py\", line 16, in <module>\n",
      "    from .path_actions import CacheUrlAction, ExtractPackageAction\n",
      "  File \"C:\\Users\\asus\\anaconda3\\lib\\site-packages\\conda\\core\\path_actions.py\", line 30, in <module>\n",
      "    from ..gateways.connection.download import download\n",
      "  File \"C:\\Users\\asus\\anaconda3\\lib\\site-packages\\conda\\gateways\\connection\\download.py\", line 14, in <module>\n",
      "    from .session import CondaSession\n",
      "  File \"C:\\Users\\asus\\anaconda3\\lib\\site-packages\\conda\\gateways\\connection\\session.py\", line 13, in <module>\n",
      "    from .adapters.s3 import S3Adapter\n",
      "  File \"C:\\Users\\asus\\anaconda3\\lib\\site-packages\\conda\\gateways\\connection\\adapters\\s3.py\", line 12, in <module>\n",
      "    import boto3\n",
      "  File \"C:\\Users\\asus\\anaconda3\\lib\\site-packages\\boto3\\__init__.py\", line 17, in <module>\n",
      "    from boto3.session import Session\n",
      "  File \"C:\\Users\\asus\\anaconda3\\lib\\site-packages\\boto3\\session.py\", line 17, in <module>\n",
      "    import botocore.session\n",
      "  File \"C:\\Users\\asus\\anaconda3\\lib\\site-packages\\botocore\\session.py\", line 26, in <module>\n",
      "    import botocore.client\n",
      "  File \"C:\\Users\\asus\\anaconda3\\lib\\site-packages\\botocore\\client.py\", line 15, in <module>\n",
      "    from botocore import waiter, xform_name\n",
      "  File \"C:\\Users\\asus\\anaconda3\\lib\\site-packages\\botocore\\waiter.py\", line 18, in <module>\n",
      "    from botocore.docs.docstring import WaiterDocstring\n",
      "  File \"C:\\Users\\asus\\anaconda3\\lib\\site-packages\\botocore\\docs\\__init__.py\", line 15, in <module>\n",
      "    from botocore.docs.service import ServiceDocumenter\n",
      "  File \"C:\\Users\\asus\\anaconda3\\lib\\site-packages\\botocore\\docs\\service.py\", line 14, in <module>\n",
      "    from botocore.docs.client import ClientDocumenter, ClientExceptionsDocumenter\n",
      "  File \"C:\\Users\\asus\\anaconda3\\lib\\site-packages\\botocore\\docs\\client.py\", line 17, in <module>\n",
      "    from botocore.docs.example import ResponseExampleDocumenter\n",
      "  File \"C:\\Users\\asus\\anaconda3\\lib\\site-packages\\botocore\\docs\\example.py\", line 13, in <module>\n",
      "    from botocore.docs.shape import ShapeDocumenter\n",
      "  File \"C:\\Users\\asus\\anaconda3\\lib\\site-packages\\botocore\\docs\\shape.py\", line 19, in <module>\n",
      "    from botocore.utils import is_json_value_header\n",
      "  File \"C:\\Users\\asus\\anaconda3\\lib\\site-packages\\botocore\\utils.py\", line 37, in <module>\n",
      "    import botocore.httpsession\n",
      "  File \"C:\\Users\\asus\\anaconda3\\lib\\site-packages\\botocore\\httpsession.py\", line 45, in <module>\n",
      "    from urllib3.contrib.pyopenssl import (\n",
      "  File \"C:\\Users\\asus\\anaconda3\\lib\\site-packages\\urllib3\\contrib\\pyopenssl.py\", line 50, in <module>\n",
      "    import OpenSSL.crypto\n",
      "  File \"C:\\Users\\asus\\anaconda3\\lib\\site-packages\\OpenSSL\\__init__.py\", line 8, in <module>\n",
      "    from OpenSSL import crypto, SSL\n",
      "  File \"C:\\Users\\asus\\anaconda3\\lib\\site-packages\\OpenSSL\\crypto.py\", line 3279, in <module>\n",
      "    _lib.OpenSSL_add_all_algorithms()\n",
      "AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\asus\\anaconda3\\Scripts\\conda-script.py\", line 12, in <module>\n",
      "    sys.exit(main())\n",
      "  File \"C:\\Users\\asus\\anaconda3\\lib\\site-packages\\conda\\cli\\main.py\", line 129, in main\n",
      "    return conda_exception_handler(main, *args, **kwargs)\n",
      "  File \"C:\\Users\\asus\\anaconda3\\lib\\site-packages\\conda\\exceptions.py\", line 1413, in conda_exception_handler\n",
      "    return_value = exception_handler(func, *args, **kwargs)\n",
      "  File \"C:\\Users\\asus\\anaconda3\\lib\\site-packages\\conda\\exceptions.py\", line 1128, in __call__\n",
      "    return self.handle_exception(exc_val, exc_tb)\n",
      "  File \"C:\\Users\\asus\\anaconda3\\lib\\site-packages\\conda\\exceptions.py\", line 1170, in handle_exception\n",
      "    return self.handle_unexpected_exception(exc_val, exc_tb)\n",
      "  File \"C:\\Users\\asus\\anaconda3\\lib\\site-packages\\conda\\exceptions.py\", line 1181, in handle_unexpected_exception\n",
      "    self.print_unexpected_error_report(error_report)\n",
      "  File \"C:\\Users\\asus\\anaconda3\\lib\\site-packages\\conda\\exceptions.py\", line 1251, in print_unexpected_error_report\n",
      "    from .cli.main_info import get_env_vars_str, get_main_info_str\n",
      "  File \"C:\\Users\\asus\\anaconda3\\lib\\site-packages\\conda\\cli\\main_info.py\", line 19, in <module>\n",
      "    from ..core.index import _supplement_index_with_system\n",
      "  File \"C:\\Users\\asus\\anaconda3\\lib\\site-packages\\conda\\core\\index.py\", line 14, in <module>\n",
      "    from .package_cache_data import PackageCacheData\n",
      "  File \"C:\\Users\\asus\\anaconda3\\lib\\site-packages\\conda\\core\\package_cache_data.py\", line 16, in <module>\n",
      "    from .path_actions import CacheUrlAction, ExtractPackageAction\n",
      "  File \"C:\\Users\\asus\\anaconda3\\lib\\site-packages\\conda\\core\\path_actions.py\", line 30, in <module>\n",
      "    from ..gateways.connection.download import download\n",
      "  File \"C:\\Users\\asus\\anaconda3\\lib\\site-packages\\conda\\gateways\\connection\\download.py\", line 14, in <module>\n",
      "    from .session import CondaSession\n",
      "  File \"C:\\Users\\asus\\anaconda3\\lib\\site-packages\\conda\\gateways\\connection\\session.py\", line 13, in <module>\n",
      "    from .adapters.s3 import S3Adapter\n",
      "  File \"C:\\Users\\asus\\anaconda3\\lib\\site-packages\\conda\\gateways\\connection\\adapters\\s3.py\", line 12, in <module>\n",
      "    import boto3\n",
      "  File \"C:\\Users\\asus\\anaconda3\\lib\\site-packages\\boto3\\__init__.py\", line 17, in <module>\n",
      "    from boto3.session import Session\n",
      "  File \"C:\\Users\\asus\\anaconda3\\lib\\site-packages\\boto3\\session.py\", line 17, in <module>\n",
      "    import botocore.session\n",
      "  File \"C:\\Users\\asus\\anaconda3\\lib\\site-packages\\botocore\\session.py\", line 26, in <module>\n",
      "    import botocore.client\n",
      "  File \"C:\\Users\\asus\\anaconda3\\lib\\site-packages\\botocore\\client.py\", line 15, in <module>\n",
      "    from botocore import waiter, xform_name\n",
      "  File \"C:\\Users\\asus\\anaconda3\\lib\\site-packages\\botocore\\waiter.py\", line 18, in <module>\n",
      "    from botocore.docs.docstring import WaiterDocstring\n",
      "  File \"C:\\Users\\asus\\anaconda3\\lib\\site-packages\\botocore\\docs\\__init__.py\", line 15, in <module>\n",
      "    from botocore.docs.service import ServiceDocumenter\n",
      "  File \"C:\\Users\\asus\\anaconda3\\lib\\site-packages\\botocore\\docs\\service.py\", line 14, in <module>\n",
      "    from botocore.docs.client import ClientDocumenter, ClientExceptionsDocumenter\n",
      "  File \"C:\\Users\\asus\\anaconda3\\lib\\site-packages\\botocore\\docs\\client.py\", line 17, in <module>\n",
      "    from botocore.docs.example import ResponseExampleDocumenter\n",
      "  File \"C:\\Users\\asus\\anaconda3\\lib\\site-packages\\botocore\\docs\\example.py\", line 13, in <module>\n",
      "    from botocore.docs.shape import ShapeDocumenter\n",
      "  File \"C:\\Users\\asus\\anaconda3\\lib\\site-packages\\botocore\\docs\\shape.py\", line 19, in <module>\n",
      "    from botocore.utils import is_json_value_header\n",
      "  File \"C:\\Users\\asus\\anaconda3\\lib\\site-packages\\botocore\\utils.py\", line 37, in <module>\n",
      "    import botocore.httpsession\n",
      "  File \"C:\\Users\\asus\\anaconda3\\lib\\site-packages\\botocore\\httpsession.py\", line 45, in <module>\n",
      "    from urllib3.contrib.pyopenssl import (\n",
      "  File \"C:\\Users\\asus\\anaconda3\\lib\\site-packages\\urllib3\\contrib\\pyopenssl.py\", line 50, in <module>\n",
      "    import OpenSSL.crypto\n",
      "  File \"C:\\Users\\asus\\anaconda3\\lib\\site-packages\\OpenSSL\\__init__.py\", line 8, in <module>\n",
      "    from OpenSSL import crypto, SSL\n",
      "  File \"C:\\Users\\asus\\anaconda3\\lib\\site-packages\\OpenSSL\\crypto.py\", line 3279, in <module>\n",
      "    _lib.OpenSSL_add_all_algorithms()\n",
      "AttributeError: module 'lib' has no attribute 'OpenSSL_add_all_algorithms'\n"
     ]
    }
   ],
   "source": [
    "conda install -n myenv jupyter"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7ab37789",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
